/**
 * Pure handler logic for /api/cli/agents/[slug] (GET pull).
 *
 * Extracted from the Next.js route so vitest can import it directly.
 */

import { flowToManifest } from "@/lib/manifest/from-flow";
import { codegen } from "@/lib/manifest/codegen";
import type { FlowRepo } from "@/lib/db/repo";
import type { AgentManifest } from "@/lib/manifest/schema";
import { requireFlowGraphV1 } from "@/lib/flow/graph-schema";

export interface PullResult {
  slug: string;
  manifest: AgentManifest;
  /** TypeScript source generated by codegen — the CLI writes this directly to agent.ts. */
  source: string;
}

/**
 * Pull an agent manifest by slug, owner-scoped.
 *
 * Returns null when the slug doesn't exist or belongs to a different owner.
 *
 * The manifest's paidCall trigger priceUsdc is enriched from the agent row —
 * the graph's meta.triggers may carry priceUsdc: 0 (the round-trip default).
 * The launch row price is the source of truth.
 */
export async function handleCliAgentPull(
  slug: string,
  ownerId: string,
  repo: FlowRepo,
): Promise<PullResult | null> {
  const agent = await repo.getAgentBySlug(slug);
  if (!agent) return null;

  // Verify ownership via the flow's ownerId
  const flow = await repo.getFlow(agent.flowId);
  if (!flow || flow.ownerId !== ownerId) return null;

  const manifest = flowToManifest(requireFlowGraphV1(flow.graph, "CLI agent pull"));

  // Enrich paidCall trigger priceUsdc from the agent row (launch row is truth;
  // graph meta.triggers carries priceUsdc: 0 from the paidCall default).
  const enrichedTriggers = manifest.triggers.map((t) =>
    t.kind === "paidCall" ? { ...t, priceUsdc: agent.priceUsdc } : t,
  );
  const enrichedManifest = { ...manifest, triggers: enrichedTriggers };

  const source = codegen(enrichedManifest);

  return { slug: agent.slug, manifest: enrichedManifest, source };
}
