import type { NodeType } from "./types";
import type {
  JsonSchema,
  NodeDefinitionV2,
  NodeConnectionSpec,
  NodeField,
  NodeFieldOption,
  NodeGroup,
  PortSpec,
} from "./node-definition-types";

export type {
  JsonSchema,
  NodeDefinitionV2,
  NodeEffect,
  NodeField,
  NodeFieldKind,
  NodeFieldOption,
  NodeGroup,
  PermissionSpec,
  NodeConnectionSpec,
  PortSpec,
} from "./node-definition-types";

const configSchema = (...keys: readonly string[]): JsonSchema => ({
  type: "object",
  properties: Object.fromEntries(keys.map((key) => [key, {}])),
});

const ports = (...ids: readonly string[]): readonly PortSpec[] =>
  ids.map((id) => ({
    id,
    label: id === "in" ? "Input" : id.charAt(0).toUpperCase() + id.slice(1),
    schema: {},
    required: true,
    cardinality: "one",
  }));

const port = (id: string, schema: JsonSchema): PortSpec => ({
  id,
  label: id === "in" ? "Input" : id.charAt(0).toUpperCase() + id.slice(1),
  schema,
  required: true,
  cardinality: "one",
});

const JSON_VALUE_SCHEMA: JsonSchema = {
  type: ["array", "boolean", "null", "number", "object", "string"],
};
const OBJECT_SCHEMA: JsonSchema = { type: "object" };
const HTTP_RESULT_SCHEMA: JsonSchema = {
  type: "object",
  required: ["status", "body"],
  properties: {
    status: { type: "integer" },
    body: JSON_VALUE_SCHEMA,
  },
};
const WEB_FETCH_RESULT_SCHEMA: JsonSchema = {
  type: "object",
  required: ["status", "url", "contentType"],
  properties: {
    status: { type: "integer" },
    url: { type: "string" },
    contentType: { type: ["string", "null"] },
    text: { type: "string" },
    json: JSON_VALUE_SCHEMA,
    price: { type: ["number", "null"] },
  },
};
const LOOP_RESULT_SCHEMA: JsonSchema = {
  type: "array",
  items: { anyOf: [{ type: "object" }, { type: "null" }] },
};
const LOOP_ERRORS_SCHEMA: JsonSchema = {
  type: "array",
  items: {
    type: "object",
    required: ["index", "error"],
    properties: {
      index: { type: "integer" },
      error: { type: "string" },
    },
  },
};

const field = (
  key: string,
  kind: NodeField["kind"],
  label: string,
  hint: string,
  options?: readonly string[] | readonly NodeFieldOption[],
): NodeField => ({ key, kind, ...(options ? { options } : {}), label, hint });

/**
 * Model tier options for the LLM node's "model" field.
 *
 * This is the client-safe catalog (see node-definition-client-boundary.test.ts —
 * its relative imports are restricted to ./types and ./node-definition-types),
 * so these mirror src/lib/billing.ts's LLM_MODEL_TIERS by value rather than
 * importing it; tests/flow/node-definitions.test.ts asserts the two stay in
 * sync, the same pattern src/app/pricing/page.tsx uses for its own blended rate.
 */
const LLM_MODEL_FIELD_OPTIONS: readonly NodeFieldOption[] = [
  { value: "", label: "Use platform default" },
  { value: "claude-haiku-4-5-20251001", label: "Fast & cheap — ~$3/1M tokens" },
  { value: "claude-sonnet-4-6", label: "Balanced (recommended) — ~$9/1M tokens" },
  { value: "claude-opus-4-6", label: "Best quality — ~$45/1M tokens" },
];

const connection = (
  key: string,
  label: string,
  hint: string,
  field: NodeConnectionSpec["field"],
  allowedKinds: NodeConnectionSpec["allowedKinds"],
  requiredHeaderNames: NodeConnectionSpec["requiredHeaderNames"],
  required = true,
): NodeConnectionSpec => ({
  key,
  label,
  hint,
  field,
  required,
  allowedKinds,
  requiredHeaderNames,
});

const EMPTY_PORTS: readonly PortSpec[] = [];
const NO_PERMISSIONS = [] as const;
const FREE = { kind: "free" } as const;
const VARIABLE = { kind: "variable" } as const;
const VARIABLE_USDC = { kind: "variable", currency: "USDC" } as const;
const estimatedUsdc = (amount: number) =>
  ({ kind: "estimated", currency: "USDC", amount }) as const;

export const NODE_GROUP_ORDER: readonly NodeGroup[] = [
  "Triggers",
  "I/O",
  "AI",
  "Logic",
  "Docs & Data",
  "Comms & CRM",
  "Finance & Ops",
  "Dev & Infra",
  "Music & IP",
  "Rails",
];

export const NODE_DEFINITION_BY_TYPE = {
  schedule: {
    definitionVersion: 1,
    type: "schedule",
    label: "Schedule",
    category: "Triggers",
    description: "Starts a flow on a five-field UTC cron schedule.",
    configSchema: configSchema("cron", "fields"),
    inputPorts: EMPTY_PORTS,
    outputPorts: [port("result", OBJECT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "calendar",
      searchableTerms: ["cron", "timer", "recurring"],
      fields: [
        field(
          "cron",
          "string",
          "Cron schedule",
          "Five-field cron expression in UTC, e.g. 0 9 * * * for daily at 09:00.",
        ),
        field(
          "fields",
          "json",
          "Default fields",
          'JSON object of default field values, e.g. {"topic": ""}. These name the arguments a caller may send when this agent is run on demand, and are what the scheduled run itself reads. A live trigger call overrides them.',
        ),
      ],
    },
  },
  webhook: {
    definitionVersion: 1,
    type: "webhook",
    label: "Webhook",
    category: "Triggers",
    description: "Starts a flow when an authenticated inbound request arrives.",
    configSchema: configSchema("note", "fields"),
    inputPorts: EMPTY_PORTS,
    outputPorts: [port("result", OBJECT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "webhook",
      searchableTerms: ["event", "request", "trigger"],
      fields: [
        field(
          "note",
          "string",
          "Source note",
          "Optional label for your own reference, e.g. GitHub push events or Stripe payment events. Purely descriptive; it has no effect on verification. A signing secret is generated for you when you launch this agent.",
        ),
        field(
          "fields",
          "json",
          "Default fields",
          'JSON object naming the body fields this trigger expects, e.g. {"repository": ""}. Unlike the note, these are real: they become this agent\'s published input contract, and the inbound payload overrides them.',
        ),
      ],
    },
  },
  input: {
    definitionVersion: 1,
    type: "input",
    label: "Input",
    category: "I/O",
    description: "Supplies trigger data and optional default fields to a flow.",
    configSchema: configSchema("fields"),
    inputPorts: EMPTY_PORTS,
    outputPorts: [port("result", OBJECT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "log-in",
      searchableTerms: ["start", "data", "fields"],
      fields: [
        field(
          "fields",
          "json",
          "Default fields",
          'JSON object of default field values, e.g. {"topic": ""}. A live trigger call overrides these when the flow runs.',
        ),
      ],
    },
  },
  output: {
    definitionVersion: 1,
    type: "output",
    label: "Output",
    category: "I/O",
    description: "Marks and labels a final flow result.",
    configSchema: configSchema("label"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", OBJECT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "log-out",
      searchableTerms: ["finish", "result", "return"],
      fields: [
        field(
          "label",
          "string",
          "Label",
          "Optional name for this output in the run ledger. Leave blank to use the node id.",
        ),
      ],
    },
  },
  "api.operation": {
    definitionVersion: 1,
    type: "api.operation",
    label: "API Operation",
    category: "Rails",
    description: "Simulates one immutable imported API operation with typed request and result ports.",
    configSchema: configSchema(
      "connectorDefinitionVersionId",
      "operationVersionId",
      "operationId",
      "connectorProjectionHash",
      "operationProjectionHash",
      "schemaHash",
      "readinessBinding",
    ),
    inputPorts: [port("request", {})],
    outputPorts: [port("result", {})],
    permissions: NO_PERMISSIONS,
    effects: ["write"],
    capabilityMode: "config-dependent",
    testMode: "stub",
    retry: "unsafe",
    cost: VARIABLE,
    prototype: { enabled: false, badge: "Prototype: simulation only" },
    ui: {
      icon: "plug-zap",
      searchableTerms: ["api", "connector", "operation", "simulation"],
      fields: [
        field("connectorDefinitionVersionId", "string", "Definition version", "Immutable connector definition version pin."),
        field("operationVersionId", "string", "Operation version", "Immutable operation version pin."),
        field("operationId", "string", "Operation ID", "Canonical imported operation identifier."),
        field("connectorProjectionHash", "string", "Connector hash", "Pinned connector projection hash."),
        field("operationProjectionHash", "string", "Operation hash", "Pinned operation projection hash."),
        field("schemaHash", "string", "Schema hash", "Pinned request/result schema hash."),
        field("readinessBinding", "json", "Readiness binding", "Optional opaque or unresolved Test readiness reference; never credential material."),
      ],
    },
  },
  "suede.styleCoach": {
    definitionVersion: 1,
    type: "suede.styleCoach",
    label: "Style Coach",
    category: "Music & IP",
    description: "Develops a creative direction from a style reference.",
    configSchema: configSchema("seed"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.05),
    ui: {
      icon: "sparkles",
      searchableTerms: ["style", "creative direction", "coach"],
      fields: [
        field(
          "seed",
          "string",
          "Seed",
          "A style reference to steer the coaching, e.g. a genre or artist name. Falls back to the upstream node's output if left blank.",
        ),
      ],
    },
  },
  "suede.lyrics": {
    definitionVersion: 1,
    type: "suede.lyrics",
    label: "Lyrics",
    category: "Music & IP",
    description: "Generates lyrics from a prompt or upstream result.",
    configSchema: configSchema("prompt"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.1),
    ui: {
      icon: "mic-2",
      searchableTerms: ["lyrics", "songwriting", "words"],
      fields: [
        field(
          "prompt",
          "string",
          "Prompt",
          "What the lyrics should be about. Falls back to the upstream node's output if left blank.",
        ),
      ],
    },
  },
  "suede.generateSong": {
    definitionVersion: 1,
    type: "suede.generateSong",
    label: "Generate Song",
    category: "Music & IP",
    description: "Generates a song from a text description.",
    configSchema: configSchema("prompt", "durationSeconds"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.5),
    ui: {
      icon: "music",
      searchableTerms: ["song", "music", "audio", "generate"],
      fields: [
        field(
          "prompt",
          "string",
          "Prompt",
          "Description of the song to generate. Falls back to the upstream node's output if left blank.",
        ),
        field(
          "durationSeconds",
          "number",
          "Duration (seconds)",
          "Target length of the generated song. Leave blank to use the default length.",
        ),
      ],
    },
  },
  "suede.analyze": {
    definitionVersion: 1,
    type: "suede.analyze",
    label: "Analyze",
    category: "Music & IP",
    description:
      "Analyzes an audio asset and returns its musical characteristics.",
    configSchema: configSchema("audioUrl"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.01),
    ui: {
      icon: "audio-lines",
      searchableTerms: ["analyze", "audio", "features"],
      fields: [
        field(
          "audioUrl",
          "string",
          "Audio URL",
          "URL of the audio file to analyze. Falls back to the upstream node's audioUrl or assetUrl if left blank.",
        ),
      ],
    },
  },
  "suede.stems": {
    definitionVersion: 1,
    type: "suede.stems",
    label: "Stems",
    category: "Music & IP",
    description: "Separates an audio asset into instrumental and vocal stems.",
    configSchema: configSchema("audioUrl"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.5),
    ui: {
      icon: "split",
      searchableTerms: ["stems", "separate", "audio"],
      fields: [
        field(
          "audioUrl",
          "string",
          "Audio URL",
          "URL of the audio file to split into stems. Falls back to the upstream node's audioUrl or assetUrl if left blank.",
        ),
      ],
    },
  },
  "suede.midi": {
    definitionVersion: 1,
    type: "suede.midi",
    label: "MIDI",
    category: "Music & IP",
    description: "Converts an audio asset to MIDI data.",
    configSchema: configSchema("audioUrl"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.25),
    ui: {
      icon: "piano",
      searchableTerms: ["midi", "notes", "audio"],
      fields: [
        field(
          "audioUrl",
          "string",
          "Audio URL",
          "URL of the audio file to convert to MIDI. Falls back to the upstream node's audioUrl or assetUrl if left blank.",
        ),
      ],
    },
  },
  "suede.mastering": {
    definitionVersion: 1,
    type: "suede.mastering",
    label: "Mastering",
    category: "Music & IP",
    description: "Masters an audio asset for polished playback.",
    configSchema: configSchema("audioUrl"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.25),
    ui: {
      icon: "sliders-horizontal",
      searchableTerms: ["master", "polish", "audio"],
      fields: [
        field(
          "audioUrl",
          "string",
          "Audio URL",
          "URL of the audio file to master. Falls back to the upstream node's audioUrl or assetUrl if left blank.",
        ),
      ],
    },
  },
  "suede.rightsLookup": {
    definitionVersion: 1,
    type: "suede.rightsLookup",
    label: "Rights Lookup",
    category: "Music & IP",
    description: "Looks up registry-backed rights data for an asset hash.",
    configSchema: configSchema("assetHash"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.015),
    ui: {
      icon: "search-check",
      searchableTerms: ["rights", "registry", "asset", "provenance"],
      fields: [
        field(
          "assetHash",
          "string",
          "Asset hash",
          "The registered asset's hash to look up. Falls back to the upstream node's assetHash if left blank; one or the other is required.",
        ),
      ],
    },
  },
  "suede.chainChat": {
    definitionVersion: 1,
    type: "suede.chainChat",
    label: "Chain Chat",
    category: "Music & IP",
    description: "Sends a message through the Suede chain chat endpoint.",
    configSchema: configSchema("message"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: estimatedUsdc(0.05),
    ui: {
      icon: "messages-square",
      searchableTerms: ["chat", "message", "chain"],
      fields: [
        field(
          "message",
          "string",
          "Message",
          "Message to send to the chain chat endpoint. Falls back to the upstream node's output if left blank.",
        ),
      ],
    },
  },
  llm: {
    definitionVersion: 1,
    type: "llm",
    label: "LLM (Claude)",
    category: "AI",
    description:
      "Generates a model response from a prompt and upstream context.",
    configSchema: configSchema("prompt", "system", "model"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", { type: "string" })],
    permissions: NO_PERMISSIONS,
    effects: ["spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: VARIABLE_USDC,
    ui: {
      icon: "brain-circuit",
      searchableTerms: ["llm", "claude", "model", "ai", "prompt"],
      fields: [
        field(
          "prompt",
          "string",
          "Prompt",
          "Instruction sent to the model. Use {{in}} in the text to insert the upstream node's output.",
        ),
        field(
          "system",
          "string",
          "System prompt",
          "Optional system instruction that sets the model's role or constraints.",
        ),
        field(
          "model",
          "select",
          "Model",
          "Cost/speed tier for this call. Each tier maps to a specific model at an increasing blended (input+output) USDC rate per 1M tokens — list prices, not the gateway's marked-up bill. Leave on \"Use platform default\" to keep the environment's configured default model.",
          LLM_MODEL_FIELD_OPTIONS,
        ),
      ],
    },
  },
  "ai.classify": {
    definitionVersion: 1,
    type: "ai.classify",
    label: "Classify",
    category: "AI",
    description: "Sorts an upstream value into one of your own labels.",
    configSchema: configSchema("labels", "instruction", "model"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", {
      type: "object",
      required: ["label", "value"],
      properties: {
        label: { type: "string" },
        value: JSON_VALUE_SCHEMA,
      },
    })],
    permissions: NO_PERMISSIONS,
    effects: ["spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: VARIABLE_USDC,
    ui: {
      icon: "tags",
      searchableTerms: ["classify", "categorise", "categorize", "label", "triage", "sort", "route", "intent", "sentiment"],
      fields: [
        field(
          "labels",
          "json",
          "Labels",
          'The complete set of allowed answers, e.g. ["urgent", "normal", "spam"]. The node fails rather than inventing a label that is not on this list.',
        ),
        field(
          "instruction",
          "string",
          "Instruction",
          "Optional guidance on how to choose, e.g. Judge the buyer's urgency, not their tone.",
        ),
        field(
          "model",
          "select",
          "Model",
          "Cost/speed tier for this call. Leave on \"Use platform default\" to keep the environment's configured default model.",
          LLM_MODEL_FIELD_OPTIONS,
        ),
      ],
    },
  },
  "ai.extract": {
    definitionVersion: 1,
    type: "ai.extract",
    label: "Extract Fields",
    category: "AI",
    description: "Pulls named fields out of messy text as a structured object.",
    configSchema: configSchema("fields", "instruction", "model"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", OBJECT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: ["spend"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    cost: VARIABLE_USDC,
    ui: {
      icon: "list-checks",
      searchableTerms: ["extract", "parse", "fields", "structured", "json", "pull", "entities", "form"],
      fields: [
        field(
          "fields",
          "json",
          "Fields",
          'Field names to pull out, e.g. ["email", "company", "budget"]. Use an object to describe each one, e.g. {"budget": "Annual spend in USD, digits only"}. A field the text does not mention comes back null.',
        ),
        field(
          "instruction",
          "string",
          "Instruction",
          "Optional guidance, e.g. Read the signature block, not the quoted reply below it.",
        ),
        field(
          "model",
          "select",
          "Model",
          "Cost/speed tier for this call. Leave on \"Use platform default\" to keep the environment's configured default model.",
          LLM_MODEL_FIELD_OPTIONS,
        ),
      ],
    },
  },
  "suede.registerIp": {
    definitionVersion: 1,
    type: "suede.registerIp",
    label: "Register IP",
    category: "Rails",
    description:
      "Registers an upstream asset with the Suede IP Registry on Base.",
    configSchema: configSchema("title", "description", "licenseTemplate"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["write", "publish"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "badge-check",
      searchableTerms: ["register", "ip", "rights", "provenance"],
      fields: [
        field(
          "title",
          "string",
          "Title",
          "Title to register the asset under. Leave blank to register it untitled.",
        ),
        field(
          "description",
          "textarea",
          "Description",
          "Optional public description stored with the registered asset.",
        ),
        field(
          "licenseTemplate",
          "string",
          "License template",
          "License to attach, e.g. all-rights-reserved or cc-by. Defaults to all-rights-reserved.",
        ),
      ],
    },
  },
  "suede.royaltySplit": {
    definitionVersion: 1,
    type: "suede.royaltySplit",
    label: "Royalty Split",
    category: "Rails",
    description: "Builds a basis-point royalty split table for an asset.",
    configSchema: configSchema("splits"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "git-fork",
      searchableTerms: ["royalty", "split", "payee", "bps"],
      fields: [
        field(
          "splits",
          "json",
          "Splits",
          'JSON array of {payee, bps} objects, e.g. [{"payee": "alice", "bps": 6000}]. bps is basis points out of 10000 (10000 = 100%); the total across all entries must not exceed 10000.',
        ),
      ],
    },
  },
  http: {
    definitionVersion: 1,
    type: "http",
    label: "HTTP Request",
    category: "Logic",
    description:
      "Calls an HTTP endpoint with a configurable method, headers, and body.",
    configSchema: configSchema("method", "url", "headers", "body", "timeoutMs"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "headers",
      "HTTP authentication",
      "Optional stored authentication headers for this request.",
      "headers",
      ["api_key", "bearer", "basic", "custom_headers"],
      [],
      false,
    )],
    effects: ["read", "write", "delete", "send"],
    capabilityMode: "config-dependent",
    testMode: "stub",
    retry: "idempotency-required",
    cost: VARIABLE,
    ui: {
      icon: "globe-2",
      searchableTerms: ["http", "api", "rest", "request", "webhook"],
      fields: [
        field(
          "method",
          "select",
          "Method",
          "HTTP method for the request. Defaults to GET.",
          ["GET", "POST", "PUT", "PATCH", "DELETE"],
        ),
        field(
          "url",
          "string",
          "URL",
          "Full https URL to call. Use {{in}} to insert the upstream node's output. Requests to private, loopback, and link-local addresses are blocked.",
        ),
        field(
          "headers",
          "json",
          "Headers",
          'JSON object of non-secret request headers, e.g. {"Accept": "application/json"}. Add authentication through an opaque Connection binding.',
        ),
        field(
          "body",
          "textarea",
          "Body",
          "Request body sent with POST, PUT, and PATCH. Use {{in}} to insert the upstream node's output.",
        ),
        field(
          "timeoutMs",
          "number",
          "Timeout (ms)",
          "How long to wait before giving up. Defaults to 10000 and is capped at 30000.",
        ),
      ],
    },
  },
  transform: {
    definitionVersion: 1,
    type: "transform",
    label: "Transform",
    category: "Logic",
    description: "Reshapes upstream data with the local expression language.",
    configSchema: configSchema("expression"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", JSON_VALUE_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "wand-sparkles",
      searchableTerms: ["transform", "reshape", "map", "expression"],
      fields: [
        field(
          "expression",
          "textarea",
          "Expression",
          "Reshape the upstream value with a small expression, not code. Use in.field or in.items[0].id to read data, plus arithmetic, comparisons, and { key: value } to build a new object. Helpers: len, upper, lower, trim, join, split, map, get, jsonParse, jsonStringify, number, string, default. Example: { email: in.user.email, count: len(in.items) }.",
        ),
      ],
    },
  },
  "docs.extractText": {
    definitionVersion: 1,
    type: "docs.extractText",
    label: "Extract PDF Text",
    category: "Docs & Data",
    description: "Extracts plain text from a PDF's raw bytes.",
    configSchema: configSchema("fileBase64"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["text", "pageCount"],
        properties: { text: { type: "string" }, pageCount: { type: "integer" } },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "file-text",
      searchableTerms: ["pdf", "extract", "text", "document"],
      fields: [
        field(
          "fileBase64",
          "textarea",
          "PDF (base64)",
          "The PDF's bytes, base64-encoded. Falls back to the upstream node's output if left blank. This node reads bytes given to it directly — it does not fetch a URL.",
        ),
      ],
    },
  },
  "resource.query": {
    definitionVersion: 1,
    type: "resource.query",
    label: "Resource Query",
    category: "Docs & Data",
    description: "Queries one exact approved Resource Pack version through its public field allowlists.",
    configSchema: {
      type: "object",
      additionalProperties: false,
      required: [
        "resourceProductId",
        "packVersionId",
        "resourcePackContentHash",
        "filterFields",
        "returnFields",
      ],
      properties: {
        resourceProductId: { type: "string" },
        packVersionId: { type: "string" },
        resourcePackContentHash: { type: "string" },
        filterFields: { type: "array", items: { type: "string" } },
        returnFields: { type: "array", items: { type: "string" } },
        limit: { type: "integer", minimum: 1, maximum: 100 },
      },
    },
    inputPorts: [{
      id: "filters",
      label: "Filters",
      schema: { type: "object" },
      required: true,
      cardinality: "one",
    }],
    outputPorts: [
      port("result", { type: "array", items: { type: "object" } }),
      port("resourceReceipt", {
        type: "object",
        required: [
          "resourceProductId",
          "resourceVersion",
          "semanticHash",
          "freshness",
          "evidence",
          "unknowns",
          "conflicts",
          "outputSchemaValid",
        ],
        properties: {
          resourceProductId: { type: "string" },
          resourceVersion: { type: "string" },
          semanticHash: { type: "string" },
          freshness: { enum: ["fresh", "stale", "mixed"] },
          evidence: { type: "array", items: { type: "object" } },
          unknowns: { type: "array", items: { type: "string" } },
          conflicts: { type: "array", items: { type: "string" } },
          outputSchemaValid: { type: "boolean" },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: ["read"],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "database-search",
      searchableTerms: ["resource", "pack", "query", "foundry", "data"],
      fields: [
        field("resourceProductId", "string", "Resource product", "Exact owner-scoped Resource Product id."),
        field("packVersionId", "string", "Pack version", "Exact approved or Live pack version id."),
        field("resourcePackContentHash", "string", "Content hash", "Pinned SHA-256 semantic content hash."),
        field("filterFields", "json", "Filter fields", "Public filter-field allowlist copied from the pack contract."),
        field("returnFields", "json", "Return fields", "Public return-field allowlist copied from the pack contract."),
        field("limit", "number", "Limit", "Optional result limit from 1 to 100."),
      ],
    },
  },
  "docs.extractDocx": {
    definitionVersion: 1,
    type: "docs.extractDocx",
    label: "Extract DOCX Text",
    category: "Docs & Data",
    description: "Extracts plain text from a Word document's raw bytes.",
    configSchema: configSchema("fileBase64"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["text"],
        properties: { text: { type: "string" } },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "file-text",
      searchableTerms: ["docx", "word", "extract", "text", "document"],
      fields: [
        field(
          "fileBase64",
          "textarea",
          "DOCX (base64)",
          "The .docx file's bytes, base64-encoded. Falls back to the upstream node's output if left blank. This node reads bytes given to it directly — it does not fetch a URL.",
        ),
      ],
    },
  },
  "docs.knowledgeSearch": {
    definitionVersion: 1,
    type: "docs.knowledgeSearch",
    label: "Knowledge Search",
    category: "Docs & Data",
    description: "Retrieves the passages most relevant to a query from a small set of documents.",
    configSchema: configSchema("query", "documents", "topK", "chunkWords"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["matches"],
        properties: {
          matches: {
            type: "array",
            items: {
              type: "object",
              required: ["text", "score", "documentIndex", "chunkIndex"],
              properties: {
                text: { type: "string" },
                score: { type: "number" },
                documentIndex: { type: "integer" },
                chunkIndex: { type: "integer" },
                documentId: { type: "string" },
              },
            },
          },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "search",
      searchableTerms: ["knowledge", "search", "retrieval", "rag", "documents", "context"],
      fields: [
        field(
          "query",
          "string",
          "Query",
          "The question or topic to search the documents for.",
        ),
        field(
          "documents",
          "json",
          "Documents (JSON)",
          'An array of documents to search, e.g. [{ "id": "doc-1", "text": "..." }]. Falls back to the upstream node\'s output (a single extracted document or an array of them) if left blank.',
        ),
        field(
          "topK",
          "number",
          "Top K",
          "How many of the most relevant passages to return. Defaults to 3.",
        ),
        field(
          "chunkWords",
          "number",
          "Chunk size (words)",
          "How many words per passage chunk before ranking. Defaults to 150.",
        ),
      ],
    },
  },
  "docs.generateReportPdf": {
    definitionVersion: 1,
    type: "docs.generateReportPdf",
    label: "Generate Text Report PDF",
    category: "Docs & Data",
    description: "Renders a title and bounded plain-text sections into a downloadable PDF.",
    configSchema: configSchema("title", "fileName", "content", "sections"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["fileBase64", "fileName", "mimeType", "sectionCount", "byteCount"],
        properties: {
          fileBase64: { type: "string" },
          fileName: { type: "string" },
          mimeType: { type: "string" },
          sectionCount: { type: "integer" },
          byteCount: { type: "integer" },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "file-text",
      searchableTerms: ["report", "pdf", "document", "artifact", "export", "generate"],
      featured: true,
      fields: [
        field("title", "string", "Report title", "Shown at the top of the generated PDF."),
        field("fileName", "string", "File name", "Downloaded filename. The .pdf extension is added when omitted."),
        field("content", "textarea", "Report content", "Plain report text. Falls back to the upstream output when sections are not supplied."),
        field("sections", "json", "Sections (JSON)", 'Optional structured sections, e.g. [{ "heading": "Summary", "body": "..." }].'),
      ],
    },
  },
  "data.parseSpreadsheet": {
    definitionVersion: 1,
    type: "data.parseSpreadsheet",
    label: "Parse Spreadsheet",
    category: "Docs & Data",
    description: "Parses CSV or XLSX bytes into an array of row objects.",
    configSchema: configSchema("fileBase64", "format", "sheetName"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["rows", "rowCount"],
        properties: { rows: { type: "array" }, rowCount: { type: "integer" } },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "table",
      searchableTerms: ["csv", "xlsx", "excel", "spreadsheet", "parse", "data"],
      fields: [
        field(
          "fileBase64",
          "textarea",
          "File (base64)",
          "The CSV or XLSX file's bytes, base64-encoded. Falls back to the upstream node's output if left blank.",
        ),
        field(
          "format",
          "select",
          "Format",
          "Whether the bytes above are CSV or XLSX.",
          ["csv", "xlsx"],
        ),
        field(
          "sheetName",
          "string",
          "Sheet name",
          "XLSX only. Leave blank to use the first sheet.",
        ),
      ],
    },
  },
  "data.filterRows": {
    definitionVersion: 1,
    type: "data.filterRows",
    label: "Filter and Clean Rows",
    category: "Docs & Data",
    description: "Filters, removes empty or duplicate rows, projects fields, and stable-sorts structured data.",
    configSchema: configSchema(
      "rows",
      "filters",
      "dropEmptyRows",
      "dedupe",
      "dedupeBy",
      "selectFields",
      "sortBy",
      "sortDirection",
      "limit",
    ),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["rows", "rowCount", "sourceRowCount", "filteredCount", "duplicateCount", "emptyCount", "truncatedCount", "appliedRules"],
        properties: {
          rows: { type: "array" },
          rowCount: { type: "integer" },
          sourceRowCount: { type: "integer" },
          filteredCount: { type: "integer" },
          duplicateCount: { type: "integer" },
          emptyCount: { type: "integer" },
          truncatedCount: { type: "integer" },
          appliedRules: { type: "object" },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "filter",
      searchableTerms: ["filter", "rows", "dedupe", "sort", "clean", "project", "csv", "xlsx"],
      featured: true,
      fields: [
        field("rows", "json", "Rows (JSON)", "Optional row array. Leave blank to use an upstream { rows } result."),
        field("filters", "json", "Filters (JSON)", 'Up to 20 filters, e.g. [{ "field": "status", "operator": "equals", "value": "active" }].'),
        field("dropEmptyRows", "boolean", "Drop empty rows", "Remove rows whose values are all blank."),
        field("dedupe", "boolean", "Remove duplicates", "Deduplicate by the selected fields, or by the complete row when no fields are selected."),
        field("dedupeBy", "json", "Dedupe fields (JSON)", 'Optional field-name array, e.g. ["email"].'),
        field("selectFields", "json", "Keep fields (JSON)", 'Optional projected field-name array, e.g. ["email", "status"].'),
        field("sortBy", "string", "Sort field", "Optional field used for a stable numeric or text sort."),
        field("sortDirection", "select", "Sort direction", "Ascending or descending.", ["asc", "desc"]),
        field("limit", "number", "Maximum rows", "Return at most this many rows, up to 10,000."),
      ],
    },
  },
  "data.generateSpreadsheet": {
    definitionVersion: 1,
    type: "data.generateSpreadsheet",
    label: "Generate Spreadsheet",
    category: "Docs & Data",
    description: "Generates a downloadable XLSX workbook from structured rows.",
    configSchema: configSchema("rows", "fileName", "sheetName"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["fileBase64", "fileName", "mimeType", "rowCount", "columnCount", "byteCount"],
        properties: {
          fileBase64: { type: "string" },
          fileName: { type: "string" },
          mimeType: { type: "string" },
          rowCount: { type: "integer" },
          columnCount: { type: "integer" },
          byteCount: { type: "integer" },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "table",
      searchableTerms: ["xlsx", "excel", "spreadsheet", "export", "workbook", "generate"],
      featured: true,
      fields: [
        field("rows", "json", "Rows (JSON)", "Optional row array. Leave blank to use an upstream { rows } result."),
        field("fileName", "string", "File name", "Downloaded filename. The .xlsx extension is added when omitted."),
        field("sheetName", "string", "Sheet name", "Worksheet name, up to 31 characters."),
      ],
    },
  },
  "web.fetchUrl": {
    definitionVersion: 1,
    type: "web.fetchUrl",
    label: "Fetch a URL",
    category: "Docs & Data",
    description:
      "Fetches a URL with a read-only GET and returns bounded page text, parsed JSON, or a matched price number.",
    configSchema: configSchema("url", "extract", "pricePattern", "maxChars"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", WEB_FETCH_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: ["read"],
    capabilityMode: "config-dependent",
    testMode: "stub",
    retry: "safe",
    cost: VARIABLE,
    ui: {
      icon: "link",
      searchableTerms: ["fetch", "url", "web", "page", "scrape", "monitor", "price"],
      fields: [
        field(
          "url",
          "string",
          "URL",
          "Full http(s) URL to fetch with a read-only GET. Use {{in}} to insert an upstream value, e.g. {{in.url}}. Requests to private, loopback, and link-local addresses are blocked.",
        ),
        field(
          "extract",
          "select",
          "Extract",
          "How to shape the response: readable page text (HTML stripped), parsed JSON, or the raw body.",
          [
            { value: "text", label: "Readable text" },
            { value: "json", label: "Parsed JSON" },
            { value: "raw", label: "Raw body" },
          ],
        ),
        field(
          "pricePattern",
          "string",
          "Price pattern",
          "Optional regex whose first capture group is a number, e.g. \\$([0-9,.]+). When set, the first match is returned as a numeric price.",
        ),
        field(
          "maxChars",
          "number",
          "Max characters",
          "Upper bound on returned text length. Defaults to 20000 and is capped at 200000.",
        ),
      ],
    },
  },
  "comms.slackMessage": {
    definitionVersion: 1,
    type: "comms.slackMessage",
    label: "Slack Message",
    category: "Comms & CRM",
    description: "Posts a message to a Slack incoming webhook.",
    configSchema: configSchema("text", "channel"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "connection",
      "Slack webhook",
      "A custom-header connection containing the Slack webhook endpoint.",
      "webhook",
      ["custom_headers"],
      ["x-suede-webhook-url"],
    )],
    effects: ["send"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "message-square",
      searchableTerms: ["slack", "message", "notify", "webhook", "chat"],
      fields: [
        field(
          "text",
          "textarea",
          "Message",
          "Message text. Use {{in}} to insert the upstream node's output. The webhook URL is bound through a Connection, never typed here.",
        ),
        field(
          "channel",
          "string",
          "Channel override",
          "Optional. Only honored by Slack workspaces that still allow a webhook to post to a channel other than the one it was created for.",
        ),
      ],
    },
  },
  "comms.crmWebhook": {
    definitionVersion: 1,
    type: "comms.crmWebhook",
    label: "CRM Webhook",
    category: "Comms & CRM",
    description: "Sends a JSON record to any CRM or automation webhook.",
    configSchema: configSchema("record"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "connection",
      "CRM webhook",
      "A custom-header connection containing the CRM webhook endpoint and optional authorization.",
      "webhook",
      ["custom_headers"],
      ["x-suede-webhook-url"],
    )],
    effects: ["send"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "webhook",
      searchableTerms: ["crm", "webhook", "salesforce", "hubspot", "record", "contact"],
      fields: [
        field(
          "record",
          "json",
          "Record",
          'JSON object to send, e.g. { "email": "{{in.email}}", "stage": "qualified" }. The endpoint URL and an optional bearer token are bound through a Connection, never typed here.',
        ),
      ],
    },
  },
  "devops.githubRead": {
    definitionVersion: 1,
    type: "devops.githubRead",
    label: "GitHub Read",
    category: "Dev & Infra",
    description: "Reads an issue, a pull request, or a filtered issue list from GitHub.",
    configSchema: configSchema("repo", "resource", "number", "state", "labels", "limit"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "connection",
      "GitHub token",
      "A stored GitHub access connection that can read the repository.",
      "headers",
      ["bearer"],
      ["authorization"],
    )],
    // "read" alone would classify this as pure local work, because a local
    // read (extracting text from a document) is the usual meaning. This node
    // is free but still reaches a third party, so it also discloses "send":
    // that is what engages the dry-run guard. Over-disclosing capability is
    // allowed; under-disclosing is not.
    effects: ["read", "send"],
    capabilityMode: "config-dependent",
    testMode: "stub",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "github",
      searchableTerms: ["github", "read", "fetch", "issue", "pr", "pull request", "triage", "list", "backlog"],
      fields: [
        field(
          "repo",
          "string",
          "Repository",
          'In the form "owner/repo".',
        ),
        field(
          "resource",
          "select",
          "Read",
          "One issue, one pull request, or a filtered list of issues.",
          [
            { value: "issue", label: "One issue" },
            { value: "pullRequest", label: "One pull request" },
            { value: "issues", label: "Issue list" },
          ],
        ),
        field(
          "number",
          "number",
          "Number",
          "The issue or pull-request number. Required unless you are reading a list.",
        ),
        field(
          "state",
          "select",
          "State",
          "List only. Which issues to return.",
          ["open", "closed", "all"],
        ),
        field(
          "labels",
          "string",
          "Labels",
          'List only. Optional comma-separated label filter, e.g. "bug,needs-triage".',
        ),
        field(
          "limit",
          "number",
          "Limit",
          "List only. How many issues to return, 1 to 100. Defaults to 30.",
        ),
      ],
    },
  },
  "devops.githubIssue": {
    definitionVersion: 1,
    type: "devops.githubIssue",
    label: "GitHub Issue",
    category: "Dev & Infra",
    description: "Creates or comments on a GitHub issue via the REST API.",
    configSchema: configSchema("repo", "action", "issueNumber", "title", "body"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "connection",
      "GitHub token",
      "A stored GitHub access connection that can create or comment on issues.",
      "headers",
      ["bearer"],
      ["authorization"],
    )],
    effects: ["send"],
    capabilityMode: "config-dependent",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "github",
      searchableTerms: ["github", "issue", "pr", "comment", "dev", "ci"],
      fields: [
        field(
          "repo",
          "string",
          "Repository",
          'In the form "owner/repo".',
        ),
        field(
          "action",
          "select",
          "Action",
          "Create a new issue, or comment on an existing one.",
          ["create", "comment"],
        ),
        field(
          "issueNumber",
          "number",
          "Issue number",
          "Required for comment. Ignored for create.",
        ),
        field(
          "title",
          "string",
          "Title",
          "Required for create. Use {{in}} to insert the upstream node's output.",
        ),
        field(
          "body",
          "textarea",
          "Body",
          "Issue or comment body. Use {{in}} to insert the upstream node's output. The GitHub token is bound through a Connection, never typed here.",
        ),
      ],
    },
  },
  "devops.githubWorkflowDispatch": {
    definitionVersion: 1,
    type: "devops.githubWorkflowDispatch",
    label: "GitHub Workflow Dispatch",
    category: "Dev & Infra",
    description: "Triggers a workflow_dispatch event via the GitHub REST API.",
    configSchema: configSchema("repo", "workflowFile", "ref", "inputs"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", HTTP_RESULT_SCHEMA)],
    permissions: NO_PERMISSIONS,
    connections: [connection(
      "connection",
      "GitHub token",
      "A stored GitHub access connection that can dispatch the selected workflow.",
      "headers",
      ["bearer"],
      ["authorization"],
    )],
    effects: ["send"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "github",
      searchableTerms: ["github", "actions", "workflow", "dispatch", "ci", "trigger"],
      fields: [
        field(
          "repo",
          "string",
          "Repository",
          'In the form "owner/repo".',
        ),
        field(
          "workflowFile",
          "string",
          "Workflow file",
          "The workflow file's name, e.g. \"deploy.yml\".",
        ),
        field(
          "ref",
          "string",
          "Git ref",
          'Branch or tag to run on, e.g. "main".',
        ),
        field(
          "inputs",
          "json",
          "Workflow inputs",
          "JSON object matching the workflow's declared workflow_dispatch inputs. The GitHub token is bound through a Connection, never typed here.",
        ),
      ],
    },
  },
  "finance.generateInvoicePdf": {
    definitionVersion: 1,
    type: "finance.generateInvoicePdf",
    label: "Generate Invoice PDF",
    category: "Finance & Ops",
    description: "Renders structured line items into a PDF invoice.",
    configSchema: configSchema(
      "invoiceNumber",
      "sellerName",
      "buyerName",
      "lineItems",
      "currency",
      "dueDate",
      "notes",
    ),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("result", {
        type: "object",
        required: ["fileBase64", "fileName", "mimeType", "byteCount", "totalAmount"],
        properties: {
          fileBase64: { type: "string" },
          fileName: { type: "string" },
          mimeType: { type: "string" },
          byteCount: { type: "integer" },
          totalAmount: { type: "number" },
        },
      }),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "receipt",
      searchableTerms: ["invoice", "receipt", "pdf", "billing", "finance"],
      fields: [
        field("invoiceNumber", "string", "Invoice number", "Falls back to the upstream node's output if left blank."),
        field("sellerName", "string", "From", "The invoice issuer's name."),
        field("buyerName", "string", "To", "The invoice recipient's name."),
        field(
          "lineItems",
          "json",
          "Line items",
          'JSON array, e.g. [{ "description": "Consulting", "quantity": 5, "unitPrice": 120 }]. Up to 200 items.',
        ),
        field("currency", "string", "Currency", 'Defaults to "USD".'),
        field("dueDate", "string", "Due date", "Optional."),
        field("notes", "textarea", "Notes", "Optional footer text."),
      ],
    },
  },
  "suede.promo": {
    definitionVersion: 1,
    type: "suede.promo",
    label: "Launch Promo",
    category: "Rails",
    description: "Creates a creator promotion campaign from a campaign brief.",
    configSchema: configSchema(
      "name",
      "brief",
      "rewardUsdc",
      "slotCap",
      "hashtags",
    ),
    inputPorts: ports("in"),
    outputPorts: ports("campaign"),
    permissions: NO_PERMISSIONS,
    effects: ["write", "publish"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "idempotency-required",
    cost: FREE,
    ui: {
      icon: "megaphone",
      searchableTerms: ["promo", "campaign", "creator", "launch"],
      fields: [
        field(
          "name",
          "string",
          "Campaign name",
          "Name shown to creators browsing the promo.",
        ),
        field(
          "brief",
          "string",
          "Brief",
          "What creators need to do to earn the reward.",
        ),
        field(
          "rewardUsdc",
          "number",
          "Reward (USDC)",
          "USDC paid per completed slot.",
        ),
        field(
          "slotCap",
          "number",
          "Slot cap",
          "Maximum number of creators who can claim a slot. Defaults to 25, max 500.",
        ),
        field(
          "hashtags",
          "json",
          "Hashtags",
          "JSON array of hashtag strings creators must include in their post, e.g. [\"#suede\", \"#newdrop\"]. Defaults to [\"#suede\"].",
        ),
      ],
    },
  },
  "suede.promoClaims": {
    definitionVersion: 1,
    type: "suede.promoClaims",
    label: "Promo Claims",
    category: "Rails",
    description: "Reads Suede Promo campaign claims and verdicts (read-only mirror).",
    configSchema: configSchema("statuses", "campaignId", "limit"),
    inputPorts: ports("in"),
    outputPorts: ports("claims"),
    permissions: NO_PERMISSIONS,
    effects: ["read"],
    capabilityMode: "static",
    testMode: "stub",
    retry: "safe",
    // Variable like web.fetchUrl: reaches an external system, so the engine
    // must gate dry runs through the stub. Never surfaces a price — only
    // `estimated` costs do that.
    cost: VARIABLE,
    ui: {
      icon: "megaphone",
      searchableTerms: ["promo", "claims", "review", "verdict"],
      fields: [
        field(
          "statuses",
          "json",
          "Statuses",
          "JSON array of claim statuses to fetch, e.g. [\"inconclusive\", \"disputed\"]. Defaults to the review queue pair.",
        ),
        field(
          "campaignId",
          "string",
          "Campaign ID",
          "Optional campaign UUID to scope the read to one campaign.",
        ),
        field(
          "limit",
          "number",
          "Limit",
          "Maximum claims returned. Defaults to 200, max 500.",
        ),
      ],
    },
  },
  branch: {
    definitionVersion: 1,
    type: "branch",
    label: "Branch",
    category: "Logic",
    description: "Routes an upstream value through a true or false output.",
    configSchema: configSchema("field", "equals", "truthy"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("true", JSON_VALUE_SCHEMA), port("false", JSON_VALUE_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "git-branch",
      searchableTerms: ["branch", "condition", "if", "route"],
      fields: [
        field(
          "field",
          "string",
          "Field",
          "Key to read from the upstream value. Reads the whole value if it isn't an object or the key is missing.",
        ),
        field(
          "equals",
          "json",
          "Equals (optional)",
          "JSON value to compare the field against. Leave blank to use the truthy check below instead.",
        ),
        field(
          "truthy",
          "boolean",
          "Require truthy",
          "Used only when Equals is empty. Checked: the true branch fires when the field's value is truthy.",
        ),
      ],
    },
  },
  "logic.switch": {
    definitionVersion: 1,
    type: "logic.switch",
    label: "Switch",
    category: "Logic",
    description: "Routes an upstream value to one of four named outputs, or to fallback.",
    configSchema: configSchema("field", "cases"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [
      port("a", JSON_VALUE_SCHEMA),
      port("b", JSON_VALUE_SCHEMA),
      port("c", JSON_VALUE_SCHEMA),
      port("d", JSON_VALUE_SCHEMA),
      port("fallback", JSON_VALUE_SCHEMA),
    ],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "split",
      searchableTerms: ["switch", "case", "route", "match", "when", "multi", "branch"],
      fields: [
        field(
          "field",
          "string",
          "Field",
          "Key to read from the upstream value. Reads the whole value if it isn't an object or the key is missing.",
        ),
        field(
          "cases",
          "json",
          "Cases",
          'Maps a matched value to an output, e.g. { "urgent": "a", "normal": "b" }. Outputs are a, b, c and d; anything unmatched leaves through fallback.',
        ),
      ],
    },
  },
  "logic.aggregate": {
    definitionVersion: 1,
    type: "logic.aggregate",
    label: "Aggregate",
    category: "Logic",
    description: "Reduces a list to a single count, sum, average, minimum or maximum.",
    configSchema: configSchema("op", "field"),
    inputPorts: [port("in", JSON_VALUE_SCHEMA)],
    outputPorts: [port("result", {
      type: "object",
      required: ["op", "value", "count"],
      properties: {
        op: { type: "string" },
        value: { type: ["number", "null"] },
        count: { type: "integer" },
      },
    })],
    permissions: NO_PERMISSIONS,
    effects: [],
    capabilityMode: "static",
    testMode: "native",
    retry: "safe",
    cost: FREE,
    ui: {
      icon: "sigma",
      searchableTerms: ["aggregate", "sum", "count", "average", "mean", "min", "max", "total", "rollup"],
      fields: [
        field(
          "op",
          "select",
          "Operation",
          "How to reduce the list.",
          [
            { value: "count", label: "Count" },
            { value: "sum", label: "Sum" },
            { value: "avg", label: "Average" },
            { value: "min", label: "Minimum" },
            { value: "max", label: "Maximum" },
          ],
        ),
        field(
          "field",
          "string",
          "Field (optional)",
          "Key to read from each row when the list holds objects. Leave blank when the list already holds numbers. Ignored by count.",
        ),
      ],
    },
  },
  subflow: {
    definitionVersion: 1,
    type: "subflow",
    label: "Subflow",
    category: "Logic",
    description: "Runs another flow as a reusable step.",
    configSchema: configSchema("flowId"),
    inputPorts: ports("in"),
    outputPorts: ports("result"),
    permissions: NO_PERMISSIONS,
    effects: ["read", "write", "delete", "send", "spend", "publish", "settle"],
    capabilityMode: "inherits-graph",
    testMode: "native",
    retry: "idempotency-required",
    cost: VARIABLE,
    ui: {
      icon: "workflow",
      searchableTerms: ["subflow", "flow", "reuse", "nested"],
      fields: [
        field(
          "flowId",
          "string",
          "Subflow ID",
          "ID of another flow to run as a step. Find it in that flow's Studio URL: /build/<flowId>.",
        ),
      ],
    },
  },
  loop: {
    definitionVersion: 1,
    type: "loop",
    label: "Loop",
    category: "Logic",
    description: "Runs a referenced flow once for each item in an array.",
    configSchema: configSchema(
      "flowId",
      "itemsPath",
      "concurrency",
      "maxIterations",
    ),
    inputPorts: ports("in"),
    outputPorts: [port("result", LOOP_RESULT_SCHEMA), port("errors", LOOP_ERRORS_SCHEMA)],
    permissions: NO_PERMISSIONS,
    effects: ["read", "write", "delete", "send", "spend", "publish", "settle"],
    capabilityMode: "inherits-graph",
    testMode: "native",
    retry: "idempotency-required",
    cost: VARIABLE,
    ui: {
      icon: "repeat-2",
      searchableTerms: ["loop", "iterate", "array", "batch"],
      fields: [
        field(
          "flowId",
          "string",
          "Subflow ID",
          "ID of another flow to run once per array item. Find it in that flow's Studio URL: /build/<flowId>.",
        ),
        field(
          "itemsPath",
          "string",
          "Items path (optional)",
          "Dot path to the array inside the upstream value, e.g. transactions. Leave blank to use the upstream value directly as the array.",
        ),
        field(
          "concurrency",
          "number",
          "Concurrency",
          "How many items run at once. Defaults to 2, capped at 4.",
        ),
        field(
          "maxIterations",
          "number",
          "Max iterations",
          "Largest array size this loop will accept, rejected with an error above this. Defaults to 50, hard-capped at 200 no matter what is entered here.",
        ),
      ],
    },
  },
} as const satisfies Record<NodeType, NodeDefinitionV2>;

export const NODE_DEFINITIONS: readonly NodeDefinitionV2[] = Object.values(
  NODE_DEFINITION_BY_TYPE,
);

export const NODE_TYPE_SET: ReadonlySet<NodeType> = new Set(
  NODE_DEFINITIONS.map((definition) => definition.type),
);

export interface NodeAvailabilityProjection {
  readonly enabled: boolean;
}

export type NodeAvailabilityMode = "visible" | "executable";

/** Preserve exhaustive registries while projecting prototype availability at public boundaries. */
export function isNodeDefinitionAvailable(
  definition: NodeDefinitionV2,
  projection: NodeAvailabilityProjection,
  mode: NodeAvailabilityMode,
): boolean {
  if (!definition.prototype) return true;
  return mode === "visible" && projection.enabled;
}

export function projectAvailableNodeDefinitions(
  projection: NodeAvailabilityProjection,
  mode: NodeAvailabilityMode,
): readonly NodeDefinitionV2[] {
  return Object.freeze(NODE_DEFINITIONS.filter((definition) =>
    isNodeDefinitionAvailable(definition, projection, mode)));
}

export function isNodeTypeAvailable(
  type: string,
  projection: NodeAvailabilityProjection,
  mode: NodeAvailabilityMode,
): type is NodeType {
  if (!NODE_TYPE_SET.has(type as NodeType)) return false;
  return isNodeDefinitionAvailable(getNodeDefinition(type as NodeType), projection, mode);
}

export function getNodeDefinition(type: NodeType): NodeDefinitionV2 {
  return NODE_DEFINITION_BY_TYPE[type];
}

export function getNodeConnectionSpec(
  type: NodeType,
  key: string,
): NodeConnectionSpec | undefined {
  return getNodeDefinition(type).connections?.find((candidate) => candidate.key === key);
}

export function nodeAllowsSecretBinding(
  type: NodeType,
  key: string,
  field: string,
): boolean {
  return getNodeConnectionSpec(type, key)?.field === field;
}
